# Generated by Django 5.1.7 on 2025-03-11 15:24

import django.db.models.deletion
import papers.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_file', models.FileField(upload_to=papers.models.paper_file_path)),
                ('status', models.CharField(choices=[('submitted', 'Yüklendi'), ('processing', 'İşleniyor'), ('reviewing', 'Değerlendiriliyor'), ('reviewed', 'Değerlendirildi'), ('revision', 'Revizyon'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi')], default='submitted', max_length=20)),
                ('keywords', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnonymizedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=papers.models.anonymized_file_path)),
                ('anonymized_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anonymized', to='papers.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PaperLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='papers.paper')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
