# Generated by Django 5.1.7 on 2025-03-27 17:51

import django.db.models.deletion
import papers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymizedpaper',
            name='encryption_key',
            field=models.CharField(blank=True, help_text='Şifreleme için kullanılan anahtar', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anonymizedpaper',
            name='encryption_method',
            field=models.CharField(default='AES', help_text='Kullanılan şifreleme yöntemi', max_length=20),
        ),
        migrations.CreateModel(
            name='AnonymizedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_text', models.CharField(help_text="PDF'de görünen anonimleştirilmiş metin", max_length=50)),
                ('original_text', models.CharField(help_text='Orijinal metin', max_length=255)),
                ('encrypted_text', models.TextField(help_text='Şifrelenmiş orijinal metin')),
                ('content_type', models.CharField(choices=[('author', 'Yazar'), ('institution', 'Kurum')], default='author', max_length=20)),
                ('page_number', models.IntegerField(help_text='İçeriğin bulunduğu sayfa numarası')),
                ('position_data', models.TextField(blank=True, help_text="İçeriğin PDF'teki konumu (JSON)", null=True)),
                ('anonymized_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymized_contents', to='papers.anonymizedpaper')),
            ],
        ),
        migrations.CreateModel(
            name='RestoredPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=papers.models.restored_file_path)),
                ('restored_at', models.DateTimeField(auto_now_add=True)),
                ('anonymized_paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restored', to='papers.anonymizedpaper')),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='restored', to='papers.paper')),
            ],
        ),
    ]
