# Generated by Django 5.1.7 on 2025-03-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_anonymizedpaper_encryption_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='detected_authors',
            field=models.TextField(blank=True, help_text='Tespit edilen yazarlar (JSON formatında)'),
        ),
        migrations.AddField(
            model_name='paper',
            name='detected_institutions',
            field=models.TextField(blank=True, help_text='Tespit edilen kurumlar (JSON formatında)'),
        ),
    ]
