# Generated by Django 5.1.7 on 2025-03-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_detected_authors_paper_detected_institutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='field',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('computer_science', 'Computer Science'), ('medicine', 'Medicine'), ('engineering', 'Engineering'), ('economics', 'Economics'), ('social_sciences', 'Social Sciences'), ('natural_sciences', 'Natural Sciences'), ('humanities', 'Humanities'), ('education', 'Education'), ('arts', 'Arts'), ('other', 'Other')], default='', help_text='Makalenin ait olduğu akademik alan', max_length=50),
        ),
    ]
