# Generated by Django 5.1.7 on 2025-03-26 17:35

import django.db.models.deletion
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('is_editor', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='papers.paper')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Atandı'), ('in_progress', 'Değerlendiriliyor'), ('completed', 'Tamamlandı')], default='assigned', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=50)),
                ('review_file', models.FileField(blank=True, null=True, upload_to=reviews.models.review_file_path)),
                ('combined_review_file', models.FileField(blank=True, null=True, upload_to=reviews.models.combined_review_file_path)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='papers.paper')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='users.user')),
            ],
        ),
    ]
