# Generated by Django 5.1.7 on 2025-03-27 17:51

import django.db.models.deletion
from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_fix_comments_not_null'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('assigned', 'Atandı'), ('in_progress', 'Değerlendiriliyor'), ('completed', 'Tamamlandı'), ('rejected', 'Reddedildi')], default='assigned', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='combined_review_file',
            field=models.FileField(blank=True, null=True, upload_to=reviews.models.combined_review_file_path),
        ),
    ]
